# as go builder
FROM golang:latest as GO_BUILD

# don't use CGO
RUN export  CGO_ENABLED=0 \
   && echo "GOPATH" 

# docker_gen depend
RUN go get github.com/robfig/glock \
   && go get github.com/ddollar/forego \
   && pwd \
   && ls -al

# get docker-gen source code
RUN go get github.com/jwilder/docker-gen \
   && pwd \
   && ls -al /go/src
RUN cd  /go/src/github.com/jwilder/docker-gen \
   && make get-deps \
   && make

# Get the docker-gen
RUN mv /go/src/github.com/jwilder/docker-gen/docker-gen /go/bin/docker-gen

# build the nginx-proxy image
FROM nginx:1.19.3
LABEL maintainer="Cuyu Tang me@expoli.tech"

# copy files from the builder
COPY --from=GO_BUILD /go/bin/* /usr/local/bin/

# Install wget and install/updates certificates
RUN apt-get update \
 && apt-get install -y -q --no-install-recommends \
    ca-certificates \
    wget \
 && apt-get clean \
 && rm -r /var/lib/apt/lists/*


# Configure Nginx and apply fix for very long server names
RUN echo "daemon off;" >> /etc/nginx/nginx.conf \
 && sed -i 's/worker_processes  1/worker_processes  auto/' /etc/nginx/nginx.conf

# Install Forego
# COPY forego /usr/local/bin/forego
RUN chmod u+x /usr/local/bin/forego \
   && chmod u+x /usr/local/bin/docker-gen

COPY network_internal.conf /etc/nginx/

COPY . /app/
WORKDIR /app/

ENV DOCKER_HOST unix:///tmp/docker.sock

VOLUME ["/etc/nginx/certs", "/etc/nginx/dhparam"]

ENTRYPOINT ["/app/docker-entrypoint.sh"]
CMD ["forego", "start", "-r"]